Assessment.Web/Models/LivroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Assessment.Web.Models
{
    public class LivroViewModel
    {
        [Display(Name = "Id")]
        public int LivroId { get; set; }

        public string Titulo { get; set; }

        public string Editora { get; set; }

        public int Ano { get; set; }

        [Display(Name = "Edição")]
        public string Edicao { get; set; }

        public bool Disponibilidade { get; set; }

        public string Comentario { get; set; }

        public virtual ICollection<AutorViewModel> Autores { get; set; }

        
    }
}

Assessment.Web/Controllers/AutorController.cs
using Assessment.Web.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Assessment.Web.Controllers
{
    [Authorize]
    public class AutorController : Controller
    {
        private HttpClient _client;

        public AutorController()
        {
            _client = new HttpClient();
            _client.BaseAddress = new Uri("https://localhost:44366/");
            //_client.BaseAddress = new Uri("http://localhost:28347/");
            _client.DefaultRequestHeaders.Accept.Clear();

            var mediaType = new MediaTypeWithQualityHeaderValue("application/json");
            _client.DefaultRequestHeaders.Accept.Add(mediaType);
        }

        //  ImageService imageService = new ImageService();

        // GET: Autor
        public ActionResult GetAll()
        {
            var response = _client.GetAsync("/api/Autors").Result;

            if (response.IsSuccessStatusCode)
            {
                var JsonString = response.Content.ReadAsStringAsync().Result;
                var autores = JsonConvert.DeserializeObject<List<AutorViewModel>>(JsonString);

                return View(autores);

            }
            return View();
        }

        // GET: Autor/Details/5
        public ActionResult Details(int id)
        {
            var response = _client.GetAsync("/api/Autors/" + id).Result;

            if (response.IsSuccessStatusCode)
            {
                var JsonString = response.Content.ReadAsStringAsync().Result;
                var autor = JsonConvert.DeserializeObject<AutorViewModel>(JsonString);

                return View(autor);

            }
            return View();
        }

        // GET: Autores/Create        
        public ActionResult Create()
        {
            return View();
        }

        // POST: Autores/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AutorViewModel autor)
        {

            var response = await _client.PostAsJsonAsync("/api/Autors", autor);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAll");
            }
            return View();
        }

        // GET: Autores/Edit/5
        public ActionResult Edit(int id)
        {

            var response = _client.GetAsync("/api/Autors/" + id).Result;

            if (response.IsSuccessStatusCode)
            {
                var JsonString = response.Content.ReadAsStringAsync().Result;
                var autor = JsonConvert.DeserializeObject<AutorViewModel>(JsonString);

                return View(autor);

            }
            return View();
        }




        // POST: Autor/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, AutorViewModel autor)
        {
            var response = await _client.PutAsJsonAsync("/api/Autors/" + id, autor);

            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("GetAll");
            }

            return View();
        }

        // GET: Autor/Delete/5
        public ActionResult Delete(int id)
        {
            var response = _client.GetAsync("/api/Autors/" + id).Result;

            if (response.IsSuccessStatusCode)
            {
                var JsonString = response.Content.ReadAsStringAsync().Result;
                var autor = JsonConvert.DeserializeObject<AutorViewModel>(JsonString);

                return View(autor);

            }
            return View();
        }

        // POST: Autor/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, FormCollection collection)
        {
            var response = await _client.DeleteAsync("/api/Autors/" + id);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAll");
            }

            return View();

        }
    }
}

Assessment.Web/Controllers/LivroController.cs
using Assessment.Web.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Assessment.Web.Controllers
{
    [Authorize]
    public class LivroController : Controller
    {
        private HttpClient _client;



        public LivroController()
        {
            _client = new HttpClient();
            _client.BaseAddress = new Uri("https://localhost:44366/");
            //_client.BaseAddress = new Uri("http://localhost:28347/");
            _client.DefaultRequestHeaders.Accept.Clear();

            var mediaType = new MediaTypeWithQualityHeaderValue("application/json");
            _client.DefaultRequestHeaders.Accept.Add(mediaType);
        }

        //  ImageService imageService = new ImageService();

        [AllowAnonymous]
        public async Task<ActionResult> GetAll()
        {
            var response = await _client.GetAsync("api/Livros");

            if (response.IsSuccessStatusCode)
            {
                var JsonString = await response.Content.ReadAsStringAsync();

                var LivroList = JsonConvert.DeserializeObject<List<LivroViewModel>>(JsonString);


                return View(LivroList);

            }
            else
            {
                return View();

            }


        }

        // GET: Livro/Details/5
        public ActionResult Details(int id)
        {
            var response = _client.GetAsync("api/Livros/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                var String = response.Content.ReadAsStringAsync().Result;
                var Book = JsonConvert.DeserializeObject<LivroViewModel>(String);
                return View(Book);
            }
            return View();
        }

        // GET: Livro/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Livro/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LivroViewModel livro)
        {
            
            var response = await _client.PostAsJsonAsync("api/Livros", livro);

            if (response.IsSuccessStatusCode)
            {
                return View("~/Views/Home/Index.cshtml");
            }
            return View();

        }

        // GET: Livro/Edit/5
        public ActionResult Edit(int id)
        {
            var response = _client.GetAsync("api/Livros/" + id).Result;

            if (response.IsSuccessStatusCode)
            {
                var JsonString = response.Content.ReadAsStringAsync().Result;

                var Book = JsonConvert.DeserializeObject<LivroViewModel>(JsonString);


                return View(Book);
            }
            return View();
        }

        // POST: Livro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int Id, LivroViewModel livro)
        {

            var response = await _client.PutAsJsonAsync("api/Livros/" + Id, livro);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAll");
            }
            return View();
        }


        // GET: Livro/Delete/5
        public ActionResult Delete(int id)
        {
            var response = _client.GetAsync("api/Livros/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                var JsonString = response.Content.ReadAsStringAsync().Result;

                var Livro = JsonConvert.DeserializeObject<LivroViewModel>(JsonString);


                return View(Livro);

            }
            else
            {
                return View();

            }
        }

        // POST: Livro/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, FormCollection collection)
        {
            var response = await _client.DeleteAsync("api/Livros/" + id);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAll");
            }

            return View();

        }

        public ActionResult AdicionarAutores(int id)
        {
            TempData["livroid"] = id;
            TempData.Keep();

            var livro = _client.GetAsync("api/Livros/" + id).Result;
            var response = _client.GetAsync("api/Autors").Result;

            if (response.IsSuccessStatusCode)
            {
                
                var JsonString = response.Content.ReadAsStringAsync().Result;
                var autores = JsonConvert.DeserializeObject<List<AutorViewModel>>(JsonString);
                var livroString = livro.Content.ReadAsStringAsync().Result;
                var livros = JsonConvert.DeserializeObject<LivroViewModel>(livroString);

                foreach (var item in livros.Autores)
                {
                    var autor = new AutorViewModel()
                    {
                        AutorId = item.AutorId,
                        Nome = item.Nome,
                        Selecionado = item.Selecionado,
                        Sobrenome = item.Sobrenome
                    };
                    foreach (var item2 in autores)
                    {
                        if (item2.AutorId == autor.AutorId)
                        {
                            item2.Selecionado = true;
                        }
                    }

                }

                TempData.Keep();

                return View(autores);

            }
            return View();
        }

        public async Task<ActionResult> FazRelacionamento(int id)
        {
            var livroid = (int)TempData["livroid"];

            var uri = "/api/Livros/?autorId=" + id + "&livroId=" + livroid;

            var response = await _client.GetAsync(uri);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAll");
            }
            else
            {
                return View();
            }
        }

        public async Task<ActionResult> DesfazRelacionamento(int id)
        {
            var livroid = (int)TempData["livroid"];

            var uri = "/api/Livros/DesfazRelacionamento/?autorId=" + id + "&livroId=" + livroid + "&difere=" + livroid;

            var response = await _client.GetAsync(uri);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAll");
            }
            else
            {
                return View();
            }
        }
    }
}

Assessment.Web/Views/Livro/AdicionarAutores.cshtml
@model IEnumerable<Assessment.Web.Models.AutorViewModel>

@{
    ViewBag.Title = "Adicionar Autores";
}

<h2>
    <button class="btn btn-default btn-lg" onclick="location.href='@Url.Action("GetAll", "Livro")'"><span class="glyphicon glyphicon glyphicon-arrow-left"></span>Retornar a lista</button>
    Adicionar Autores
</h2>
<br />
<hr />
<p>
    <button class="btn btn-block btn-default" onclick="location.href='@Url.Action("Create", "Autor")'">Criar novo autor</button>
</p>
<table class="table" style="background-color: white;">
    <tr style="background-color:aqua;">
        <th>
            @Html.DisplayNameFor(model => model.AutorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Selecionado)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AutorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Selecionado)
            </td>
            <td>
                @{
                    if (item.Selecionado == false)
                    {
                        @Html.ActionLink("Adicionar autor", "FazRelacionamento", new { id = item.AutorId }, new { @class = "btn btn-default" })
                    }
                    else
                    {
                        @Html.ActionLink("Remover autor", "DesfazRelacionamento", new { id = item.AutorId }, new { @class = "btn btn-danger" })
                    }
                }
            </td>
        </tr>
                    }

</table>

Assessment.Web/Views/Livro/Create.cshtml
@model Assessment.Web.Models.LivroViewModel

<script>
    var loadFile = function (event) {
        var output = document.getElementById('output');
        output.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

@using (Html.BeginForm("Create", "Livro", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="container">
        <h1>Cadastro de Livro</h1>
        <hr>
        <div class="row">
            <!-- left column -->
            <div class="col-md-3">
                <div class="text-center">
                    <img src="//placehold.it/100" class="avatar img-thumbnail" alt="imagecapa" id="output">
                    <h6>Trocar foto de capa</h6>

                    <input type="file" onchange="loadFile(event)" name="photo" class="form-control disabled">
                </div>
            </div>

            <!-- edit form column -->
            <div class="col-md-9 personal-info">
                <div class="alert alert-info alert-dismissable">
                    <a class="panel-close close" data-dismiss="alert">×</a>
                    <i class="fa fa-coffee"></i>
                    Verifique os dados antes de cadastrar o livro.
                </div>
                <h3>Informação do livro</h3>

                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "col-lg-3 control-label" })
                        <div class="col-lg-8" style="margin-bottom:5px;">
                            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Editora, htmlAttributes: new { @class = "col-lg-3 control-label" })
                        <div class="col-lg-8" style="margin-bottom:5px;">
                            @Html.EditorFor(model => model.Editora, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Editora, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "col-lg-3 control-label" })
                        <div class="col-lg-8" style="margin-bottom:5px;">
                            @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Edicao, htmlAttributes: new { @class = "col-lg-3 control-label" })
                        <div class="col-lg-8" style="margin-bottom:5px;">
                            @Html.EditorFor(model => model.Edicao, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Edicao, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "col-lg-3 control-label col-md-2" })
                        <div class="col-lg-8" style="margin-bottom:5px;">
                            @Html.TextAreaFor(model => model.Comentario, new
                           {
                               @class = "form-control",
                               @style = "resize:none;",
                               @rows = "5",
                               @cols = "100%"
                           })
                            @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-3">
                            <input type="submit" value="Cadastrar" class="btn btn-default btn-block" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assessment.Web/Views/Livro/Delete.cshtml
@model Assessment.Web.Models.LivroViewModel

<style>
    .alert-box {
        margin-top: 15%;
        margin-left: 25%;
        margin-right: 25%;
        height: 150px;
        font-size: 22px;
    }
</style>

<div class="alert alert-danger alert-dismissable alert-box">
    <i class="fa fa-coffee"></i>
    Tem certeza que deseja excluir o livro, @Html.DisplayFor(model => model.Titulo) .
</div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit"  style="max-width:100%" value="Deletar" class="btn btn-block btn-danger btn-lg"  /> 
        </div>
    }

Assessment.Web/Views/Livro/Details.cshtml
@model Assessment.Web.Models.LivroViewModel

<style>
    .personal-info {
        border: solid 2px;
        background-color: white;
    }
</style>
<div class="container">

    <h1> 
        <button class="btn btn-info btn-lg" onclick="location.href='@Url.Action("GetAll", "Livro")'"><span class="glyphicon glyphicon glyphicon-arrow-left"></span>Retornar a lista</button>
    Informação do Livro</h1>
    <hr>
    <div class="row">
        <!-- left column -->
        <div class="col-md-3">
            <div class="text-center">
                <img name="photo" src="//placehold.it/100" class="avatar img-thumbnail" alt="imagecapa" id="output">
            </div>
        </div>

        <div class="col-md-9">
            <div style="background-color:none; border: solid 2px;">
                <h3>@Html.DisplayFor(model => model.Titulo)</h3>
            </div>
            <div class=" row personal-info">

                <div class="form-group">
                    @Html.LabelFor(model => model.LivroId, htmlAttributes: new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-8" style="margin-bottom:5px;">
                        @Html.DisplayFor(model => model.LivroId, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-8" style="margin-bottom:5px;">
                        @Html.DisplayFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @foreach (var item in Model.Autores)
                    {
                        <div class="form-group">
                            @Html.LabelFor(model => model.Autores, htmlAttributes: new { @class = "col-lg-3 control-label" })
                            <div class="col-lg-8" style="margin-bottom:5px;">
                               @Html.DisplayFor(modelItem => item.Sobrenome) , @Html.DisplayFor(modelItem => item.Nome, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                    }
                </div>
                

                <div class="form-group">
                    @Html.LabelFor(model => model.Editora, htmlAttributes: new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-8" style="margin-bottom:5px;">
                        @Html.DisplayFor(model => model.Editora, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-8" style="margin-bottom:5px;">
                        @Html.DisplayFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Edicao, htmlAttributes: new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-8" style="margin-bottom:5px;">
                        @Html.DisplayFor(model => model.Edicao, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-8" style="margin-bottom:5px;">
                        @Html.DisplayTextFor(model => model.Comentario)
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assessment.Web/Views/Livro/FazRelacionamento.cshtml
@{
    ViewBag.Title = "FazRelacionamento";
}

<h2>FazRelacionamento</h2>

Assessment.Web/Views/Livro/GetAll.cshtml
@model IEnumerable<Assessment.Web.Models.LivroViewModel>


<div class="well well-sm">
    <strong>Category Title</strong>
    <div class="btn-group">
        <a href="#" id="list" class="btn btn-default btn-sm">
            <span class="glyphicon glyphicon-th-list">
            </span>List
        </a> <a href="#" id="grid" class="btn btn-default btn-sm">
            <span class="glyphicon glyphicon-th"></span>Grid
        </a>
    </div>
</div>
<div id="products" class="row list-group ">

    @Html.AntiForgeryToken()
    @foreach (var item in Model)
    {

        <div class="item col-xs-4 col-lg-4 ">
            <div class="thumbnail">
                @*@if (item.Image != null)
                        {
                        <div class="image col-sm-3 col-md-3">
                            <p>Imagem:</p>
                            <img class="group list-group-image" src="@Html.DisplayFor(modelItem => item.Image)" alt="...">
                        </div>

                    }*@
                <img class="group list-group-image" src="http://placehold.it/400x250/000/fff" alt="" />
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                        Titulo : @Html.DisplayFor(modelItem => item.Titulo)
                    </h4>
                    <ul>
                        <li>
                                @foreach (var item2 in item.Autores)
                                {
                                    @Html.LabelFor(modelItem => item.Autores, htmlAttributes: new { @class = "group inner list-group-item-text" }) <text> : </text>
                                    @Html.DisplayFor(modelitem2 => item2.Sobrenome, new
                                    {
                                        htmlAttributes = new { @class = "group inner list-group-item-text" } })<text>, </text>@Html.DisplayFor(modelItem2 => item2.Nome, new { htmlAttributes = new { @class = "group inner list-group-item-text" } }) <br />
                                }
                            </li>

                        <li>
                            @Html.LabelFor(modelItem => item.Editora, htmlAttributes: new { @class = "group inner list-group-item-text" }) :
                            @Html.DisplayFor(modelItem => item.Editora, new { htmlAttributes = new { @class = "group inner list-group-item-text" } })
                        </li>
                    </ul>

                    <div class="row" style="margin-top:10px;">
                        <div class="col-xs-12 col-md-6">
                            <button class="btn btn-block btn-info" style="margin-top:10px;" onclick="location.href='@Url.Action("Details", "Livro", new { id = item.LivroId })'">Informações</button>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <button class="btn btn-block btn-success" style="margin-top:10px;" onclick="location.href='@Url.Action("Create", "Emprestimo", new { id = item.LivroId})'">Alugar</button>
                        </div>
                    </div>
                    <div class="row" style="margin-top:10px;">
                        <div class="col-xs-12 col-md-12">
                            <button class="btn btn-block btn-success" onclick="location.href='@Url.Action("AdicionarAutores", "Livro", new { id = item.LivroId})'">Adicionar Autores</button>
                        </div>
                    </div>
                    <div class="row" style="margin-top:10px;">
                        <div class="col-xs-12 col-md-6">
                            <button class="btn btn-block btn-warning" style="margin-bottom:10px;" onclick="location.href='@Url.Action("Edit", "Livro", new { id = item.LivroId })'">Editar</button>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <button class="btn btn-block btn-danger" style="margin-bottom:10px;" onclick="location.href='@Url.Action("Delete", "Livro", new { id = item.LivroId })'">Excluir</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    }
</div>